import AppKit
import CryptoKit

@MainActor
final class ClipboardMonitor {
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    /// changeCount reads are effectively free, so the floor on capture latency is the
    /// poll interval itself; 0.2s halves the average detection delay the 0.4s poll had.
    private static let pollInterval: TimeInterval = 0.2
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    /// Payload extraction (pasteboard reads, SHA256 over image bytes, image file
    /// writes) runs here so copying a large screenshot cannot stall the main thread
    /// mid-summon. NSPasteboard is thread-safe for reads.
    private let captureQueue = DispatchQueue(label: "clipbar.monitor.capture", qos: .userInitiated)

    var suppressUntilChangeCount: Int = -1
    private(set) var isPaused = false

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let t = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() { timer?.invalidate(); timer = nil }

    func togglePause() { isPaused.toggle() }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        guard !isPaused else { return }
        if current == suppressUntilChangeCount { return }

        // Cheap main-actor gating first: type and source filters are the common
        // rejects, and they settle them before paying for payload extraction.
        let types = pasteboard.types ?? []
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) { return }
        if Settings.shared.ignoreConcealed,
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return }

        let declaredSourceID = Self.validatedSourceBundleID(pasteboard.string(forType: Self.sourceType))
        let front = NSWorkspace.shared.frontmostApplication
        let src: NSRunningApplication?
        if front == nil || front?.bundleIdentifier == Bundle.main.bundleIdentifier {
            src = AppController.shared.lastActiveApp
        } else {
            src = front
        }
        let bundleID: String?
        let appName: String?
        if let declaredSourceID {
            bundleID = declaredSourceID
            appName = applicationName(forBundleID: declaredSourceID)
        } else {
            bundleID = src?.bundleIdentifier
            appName = src?.localizedName
        }

        // The pasteboard is polled, so by the time a copy is noticed the user
        // may already have switched away from the app they copied from. Check the app
        // that was frontmost a moment ago as well: a false positive costs one skipped
        // clip, a false negative leaks a password into history and into iCloud.
        let ignored = Settings.shared.isIgnoringSourceApp(declaredSourceID)
            || Settings.shared.isIgnoringSourceApp(src?.bundleIdentifier)
            || Settings.shared.isIgnoringSourceApp(AppController.shared.lastActiveApp?.bundleIdentifier)
        guard !ignored else { return }

        let imagesDir = ClipboardStore.shared.imagesDirectory
        captureQueue.async {
            guard let item = Self.extractPayload(types: types,
                                                 bundleID: bundleID,
                                                 appName: appName,
                                                 imagesDir: imagesDir) else { return }
            // A newer copy landing mid-extraction means these reads are of a
            // superseded generation; drop and let the next poll take the fresh one.
            guard NSPasteboard.general.changeCount == current else { return }
            Task { @MainActor in
                ClipboardStore.shared.addCaptured(item)
                SoundEffects.playCapture()
            }
        }
    }

    /// Heavy payload extraction. Runs on `captureQueue`, not the main actor: reads
    /// only NSPasteboard (thread-safe) and immutable captured values.
    private nonisolated static func extractPayload(types: [NSPasteboard.PasteboardType],
                                                   bundleID: String?,
                                                   appName: String?,
                                                   imagesDir: URL) -> ClipItem? {
        let pasteboard = NSPasteboard.general

        func decorate(_ item: inout ClipItem) {
            item.sourceBundleID = bundleID
            item.sourceAppName = appName
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            var item = ClipItem(type: .file,
                                text: urls.map(\.lastPathComponent).joined(separator: ", "),
                                fileURLs: urls.map(\.absoluteString))
            decorate(&item)
            return item
        }

        if types.contains(.png) || types.contains(.tiff) {
            if let data = Self.pngData(pasteboard) {
                let hash = Self.sha256Hex(data)
                guard let name = ClipboardStore.writeImageFile(data, into: imagesDir) else { return nil }
                var item = ClipItem(type: .image, imageFileName: name, imageHash: hash)
                decorate(&item)
                return item
            }
        }

        let rtf = pasteboard.data(forType: .rtf)
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            let routed = ClipboardAgentMetadata.stripLeadingMarker(from: string)
            guard !routed.text.isEmpty else { return nil }
            let cleanRTF = routed.metadata == nil ? rtf : nil
            let trimmed = routed.text.trimmingCharacters(in: .whitespacesAndNewlines)
            let type: ClipType
            if cleanRTF != nil {
                type = .richText
            } else if Self.isLink(trimmed) {
                type = .link
            } else {
                type = .text
            }
            var item = ClipItem(type: type, text: routed.text, rtfData: cleanRTF, agentMetadata: routed.metadata)
            decorate(&item)
            return item
        }

        if Self.hasColorType(types), let color = NSColor(from: pasteboard) {
            var item = ClipItem(type: .color, colorHex: color.usingColorSpace(.sRGB)?.hexString)
            decorate(&item)
            return item
        }

        return nil
    }

    private nonisolated static func hasColorType(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { $0.rawValue.localizedCaseInsensitiveContains("color") }
    }

    private nonisolated static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private nonisolated static func pngData(_ pasteboard: NSPasteboard) -> Data? {
        if let data = pasteboard.data(forType: .png) { return data }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private nonisolated static func validatedSourceBundleID(_ raw: String?) -> String? {
        guard let raw, !raw.isEmpty, raw.count <= 255, raw.contains(".") else { return nil }
        let allowed = CharacterSet(charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-")
        guard raw.unicodeScalars.allSatisfy({ allowed.contains($0) }) else { return nil }
        return raw
    }

    private func applicationName(forBundleID bundleID: String) -> String? {
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID),
              let bundle = Bundle(url: url) else { return nil }
        return (bundle.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String)
            ?? (bundle.object(forInfoDictionaryKey: "CFBundleName") as? String)
    }

    private nonisolated static func isLink(_ s: String) -> Bool {
        guard !s.contains(" "), !s.contains("\n"),
              let url = URL(string: s),
              let scheme = url.scheme?.lowercased(),
              ["http", "https"].contains(scheme),
              url.host != nil else { return false }
        return true
    }
}

private extension NSColor {
    convenience init?(from pasteboard: NSPasteboard) {
        guard let objs = pasteboard.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor],
              let c = objs.first else { return nil }
        self.init(cgColor: c.cgColor)
    }
}
